### ISSUE TITLE
filter cpuinfo

### ISSUE THREAD

**Issue by fragfutter** [puppetlabs/facter#2677]
## Use Case
for each cpu core a fact with cpu information is generated. On systems with a high cpu count (for example AMD epyc with 128 cores) a lot of facts are generated.  (more then 16k facts)

## Describe the Solution You Would Like
have the possibility filter all cpuinfoinformation except cpuinfo.0

## Describe Alternatives You've Considered
blocklist cpuinfo will block all information. having the flags of the first core provides enough information for most use cases.

**Comment by joshcooper** [comment]
Hi @fragfutter facter can block an entire fact like `processors`, but not specific values within the `processors` fact. We're tracking that capability in #2658 though you're use case has been mentioned yet (the ability to exclude everything except `cpuinfo.0`. I'll add a note on that issue and close this one.

**Comment by joshcooper** [comment]
@fragfutter could you let us know where the `cpuinfo` facts are coming from? It's not part of core facter.

**Comment by fragfutter** [comment]
ohhh. That is really embarrassing. It's my very own fact which i wrote about 15 years ago.
