### ISSUE TITLE
Fix reference to unknown 'log' library in aggregate.rb

### ISSUE THREAD

**Issue by personjs** [puppetlabs/facter#2714]
## Describe the Bug
Line 115 of aggregate.rb tries to call 'log.warn', but 'log' is unknown, which breaks legacy builds.

## Expected Behavior
Custom facts using legacy aggregate reference do not cause errors to be thrown during puppet install

## Steps to Reproduce
1. Create new module with lib/facter/[customfact].rb that uses 'Facter.define_fact([name], type: :aggregate)' and 'define_resolution([name], type: :aggregate)
2. Run puppet

## Environment
 - Version facter [4.7.0] puppet [8.6.0]
 - Platform [RHEL 8]

**Comment by cthorn42** [comment]
@personjs thanks for the bug report, we'll look into this.

**Comment by joshcooper** [comment]
This should be fixed in https://github.com/puppetlabs/facter/pull/2722/commits/00bc4db614a2d97331cf1210f8261f2d965d1e1f

**Comment by joshcooper** [comment]
Fixed in https://github.com/puppetlabs/facter/pull/2722/commits/707e8f928135613033af5b9248f60254c9d17d91
