### ISSUE TITLE
Unsupported container runtime 'lxc' with facter 4.8.0+ / nightly

### ISSUE THREAD

**Issue by torstenfohrer** [puppetlabs/facter#2737]
## Describe the Bug
Since facter 4.8.0 we getting unsupported container runtime 'lxc'

Problem origin here [facter source](https://github.com/puppetlabs/facter/blame/8dfaabf794dab16267120e906002c8147a27ef8c/lib/facter/resolvers/containers.rb#L46)

## Expected Behavior
Support 'lxc' as runtime again, perhaps additional to 'lxcroot'

## Steps to Reproduce
1. Setup a lxc
2. Install puppet-agent 8.8.0 (aka 8.7.0.38.gc055f2ce8-1noble)
4. Simple run `facter` resulting in following output (stripped down)

`[2024-07-08 10:23:33.166466 ] WARN Facter::Resolvers::Containers - Container runtime, 'lxc', is unsupported, setting to, 'container_other'`

## Environment
 - Puppet agent 8.8.0, (nightly 8.7.0.38.gc055f2ce8-1noble)
 - Facter 4.8.0
 - Ubuntu 20.04, 22.04, 24.04

## Additional Context
See also at systemd source: https://github.com/systemd/systemd/blob/cd8eb9605f1a1f2fe1180382201d23548cad7a1c/src/nspawn/nspawn.c#L3500

**Comment by joshcooper** [comment]
@lollipopman https://github.com/puppetlabs/facter/commit/7bc38ccb58e6abf66d6141a3b2e9f60eb0077d71 may have broken lxc could you take a look?

**Comment by joshcooper** [comment]
This is caused by https://github.com/puppetlabs/facter/pull/2574

**Comment by aqueos** [comment]
same here on debian guest all facter virtual fail to work with lxd.

[~]: facter virtual
[2024-07-29 15:35:28.953018 ] WARN Facter::Resolvers::Containers - Container runtime, 'lxc', is unsupported, setting to, 'container_other' 
container_other

completly broke a lot of pp script and templates :(

**Comment by lollipopman** [comment]
> @lollipopman [7bc38cc](https://github.com/puppetlabs/facter/commit/7bc38ccb58e6abf66d6141a3b2e9f60eb0077d71) may have broken lxc could you take a look?

will do

**Comment by joshcooper** [comment]
Can folks on this thread try out @lollipopman patch in https://github.com/puppetlabs/facter/pull/2741?

**Comment by aqueos** [comment]
hi,

 just FYI the issue still exist for me

[~]: dpkg -l '*puppet*'|grep ii
ii  puppet-agent                 7.32.1-1focal amd64        The Puppet Agent package contains all of the elements needed to run 

[~]: puppet facts|grep virtual
Warning: Facter: Container runtime, 'lxc', is unsupported, setting to, 'container_other'
  "is_virtual": true,
  "virtual": "container_other",

i cannot follow the link to https://perforce.atlassian.net/browse/FACT-3477 to see the rest but this vital fact is still not working on lxc/lxd for me :)

best regards,
Ghislain.

**Comment by lollipopman** [comment]
I don't think the fix has made it into any release, you would need to use `git HEAD` to test.

```
$ git tag --contains c609d1c9f
```

**Comment by turchanov** [comment]
Hello! This fix has broken detection of libvirt-lxc containters!
```
Warning: Facter: Container runtime, 'lxc-libvirt', is unsupported, setting to 'container_other'
```

I think you should/must match on prefix "^lxc.*"
