### ISSUE TITLE
Facter 4.9.0 signature is missing

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/facter#2761]
## Describe the Bug

We're using the releases at https://downloads.puppetlabs.com/facter/ to build and package facter. For the 4.9.0 release, facter-4.9.0.gem.asc is missing. Can you please add it

## Expected Behavior

I expect 4.9.0.gem.asc

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

**Comment by mhashizume** [comment]
Thanks for flagging this! Our Release Engineering team has uploaded the signature and updated our release process to ensure that it's present in future releases.
