### ISSUE TITLE
dhcpcd is not running 

### ISSUE THREAD

**Issue by DevSysEngineer** [puppetlabs/facter#2773]
## Describe the Bug
When I ran factor on my server I got a lot of errors in /var/log/syslog saying dhcpcd was not running. This is correct because my server is configured with a static IP address without dhcpcd.

## Expected Behavior
No error logs

## Steps to Reproduce
1. apt-get purge dhcpcd
2. Run facter
3. Check log: tail -f /var/log/syslog -n 200

## Environment
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble

# facter --version
4.3.0

**Comment by joshcooper** [comment]
@DevSysEngineer can you include some of the errors you're seeing the log (redacted as needed)?
